### ISSUE TITLE
Stack trace from gardener logs in staging related to state.WriteHTMLStatusTo

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl-gardener#112]
```
2018/10/18 17:04:10 server.go:2979: http: panic serving 10.12.2.1:42928: runtime error: invalid memory address or nil pointer dereference
goroutine 752594 [running]:
net/http.(*conn).serve.func1(0xc00035b680)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xaa6020, 0x1189010)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/m-lab/etl-gardener/state.WriteHTMLStatusTo(0xc60920, 0xc000c58300, 0xc56da0, 0xc000229880, 0xc000036088, 0xc, 0xc00003600b, 0x10, 0x0, 0x0)
        /go/src/github.com/m-lab/etl-gardener/state/state.go:311 +0x93
main.Status(0xc5ffa0, 0xc000229880, 0xc0000cf000)
        /go/src/github.com/m-lab/etl-gardener/cmd/gardener/gardener.go:253 +0x305
net/http.HandlerFunc.ServeHTTP(0xbda488, 0xc5ffa0, 0xc000229880, 0xc0000cf000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x119ec80, 0xc5ffa0, 0xc000229880, 0xc0000cf000)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000348000, 0xc5ffa0, 0xc000229880, 0xc0000cf000)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00035b680, 0xc60920, 0xc000c58240)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by pboothe** [comment]
Obsolete.
